(function(){
 const qs=()=>new URLSearchParams(location.search);
 const norm=s=>String(s||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 function periodIndex(){const p=qs().get('donem');if(p===null)return null;const n=parseInt(p,10);return Number.isFinite(n)?Math.max(0,Math.min(9,n-1)):null}
 function focusPeriod(){const i=periodIndex();if(i===null)return;const sc=document.querySelector('.scroll');if(!sc)return;const max=Math.max(0,sc.scrollWidth-sc.clientWidth),left=max*(i/9);setTimeout(()=>sc.scrollTo({left,behavior:'smooth'}),350);setTimeout(()=>{const cols=[...document.querySelectorAll('.col-title')];const c=cols[i];if(c){c.classList.add('deep-period-focus');setTimeout(()=>c.classList.remove('deep-period-focus'),3200)}},650)}
 function openWork(){const wanted=qs().get('eser');if(!wanted)return;let tries=0;const go=()=>{const nodes=[...document.querySelectorAll('.node[data-eser]')];if(!nodes.length&&tries++<100)return setTimeout(go,80);const hit=nodes.find(n=>norm(n.dataset.eser)===norm(wanted)||norm(n.dataset.eser).includes(norm(wanted)));if(!hit)return;hit.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});hit.classList.add('deep-work-focus');setTimeout(()=>hit.click(),450);setTimeout(()=>hit.classList.remove('deep-work-focus'),3500)};go()}
 function shareState(){document.addEventListener('click',e=>{const n=e.target.closest('.node[data-eser]');if(!n)return;const u=new URL(location.href);u.searchParams.set('eser',norm(n.dataset.eser));history.replaceState({eser:n.dataset.eser},'',u)},true);document.addEventListener('click',e=>{if(!e.target.closest('.v5-close'))return;const u=new URL(location.href);u.searchParams.delete('eser');history.replaceState({},'',u)},true)}
 const css=document.createElement('style');css.textContent='.deep-period-focus{color:var(--gold)!important;text-shadow:0 0 18px color-mix(in srgb,var(--gold) 35%,transparent);transition:.25s}.deep-work-focus{outline:2px solid var(--gold)!important;outline-offset:5px;box-shadow:0 0 28px color-mix(in srgb,var(--gold) 35%,transparent)!important;z-index:30!important}';document.head.appendChild(css);
 function init(){focusPeriod();openWork();shareState()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();