(async function(){
 const [ideas,companion,world,questions,graph]=await Promise.all(['fikirHatlari','companion','dunyaParalel','sorular','dusunceGrafi'].map(x=>fetch('./data/'+x+'.json').then(r=>r.json())));
 const css=document.createElement('style');css.textContent=`
 .node.v4-dim{opacity:.08!important;filter:saturate(.18)}.node.v4-hit{box-shadow:0 0 0 2px var(--gold)!important;z-index:14!important}.v4-svg{position:fixed;inset:0;width:100vw;height:100vh;z-index:13;pointer-events:none}.v4-svg path{fill:none;stroke:var(--gold);stroke-width:2.2;stroke-linecap:round;stroke-dasharray:5 5;opacity:.9}.v4-svg circle{fill:var(--gold)}
 .v4-path{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:70;width:min(820px,90vw);background:var(--card);border:1px solid var(--gold);padding:12px;border-radius:7px;box-shadow:0 12px 35px #0006}.v4-path-title{font:17px var(--font-display);margin-bottom:7px}.v4-steps{display:flex;gap:5px;flex-wrap:wrap;align-items:center}.v4-step{font:9px var(--font-mono);border:.5px solid var(--border);border-radius:12px;padding:4px 7px}.v4-rel{font:8px var(--font-mono);color:var(--gold)}
 .v4-overlay{position:fixed;inset:0;z-index:95;background:#120d07aa;display:grid;place-items:center;padding:20px}.v4-modal{width:min(860px,96vw);max-height:88vh;overflow:auto;background:var(--card);border:1px solid var(--border);border-radius:9px;padding:25px;position:relative}.v4-modal h2{font:30px var(--font-display);margin:0 35px 7px 0}.v4-close{position:absolute;right:15px;top:12px;background:none;border:0;color:var(--text);font-size:22px;cursor:pointer}.v4-k{font:9px var(--font-mono);letter-spacing:1px;color:var(--gold);text-transform:uppercase;margin-bottom:7px}.v4-lead{font:14px/1.5 var(--font-display);color:var(--text-sec);margin-bottom:17px}.v4-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v4-choice{padding:13px;text-align:left;background:var(--bg);border:.5px solid var(--border);border-radius:6px;color:var(--text);font:15px var(--font-display);cursor:pointer}.v4-choice:hover{border-color:var(--gold)}
 .v4-world{border-top:.5px solid var(--border);padding:14px 0}.v4-world h3{font:18px var(--font-display);margin:0 0 8px}.v4-cols{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v4-col{background:var(--bg);padding:10px;border-radius:5px;font:12px/1.45 var(--font-display)}.v4-col b{display:block;font:9px var(--font-mono);color:var(--gold);margin-bottom:4px}.v4-event{font:12px/1.45 var(--font-display);color:var(--text-sec);margin-top:7px}
 .v4-ring{width:120px;height:120px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(var(--gold) var(--p),var(--bg) 0);position:relative;margin:5px auto 18px}.v4-ring:after{content:'';position:absolute;inset:9px;background:var(--card);border-radius:50%}.v4-ring b{z-index:1;font:25px var(--font-display)}.v4-bar{margin:9px 0}.v4-barhead{display:flex;justify-content:space-between;font:10px var(--font-mono);margin-bottom:3px}.v4-track{height:6px;background:var(--bg);border-radius:4px;overflow:hidden}.v4-fill{height:100%;background:var(--gold)}
 .v4-card{position:fixed;right:0;top:0;height:100vh;width:min(450px,92vw);z-index:85;background:var(--card);border-left:1px solid var(--border);padding:25px;overflow:auto;transform:translateX(105%);transition:.25s}.v4-card.open{transform:none}.v4-card h2{font:26px var(--font-display);margin:0 30px 10px 0}.v4-block{border-top:.5px solid var(--border);padding:13px 0}.v4-block label{display:block;font:9px var(--font-mono);color:var(--gold);text-transform:uppercase;margin-bottom:5px}.v4-block div{font:14px/1.5 var(--font-display)}.v4-tags{display:flex;gap:5px;flex-wrap:wrap}.v4-tag,.v4-jump{font:9px var(--font-mono);border:.5px solid var(--border);padding:4px 7px;border-radius:11px;background:var(--bg);color:var(--text)}.v4-jump{cursor:pointer}.v4-jump:hover{border-color:var(--gold)}
 .v4-form{display:grid;grid-template-columns:1fr auto 1fr;gap:10px;align-items:end}.v4-field label{display:block;font:9px var(--font-mono);color:var(--gold);margin-bottom:5px;text-transform:uppercase}.v4-field select{width:100%;background:var(--bg);color:var(--text);border:.5px solid var(--border);padding:9px;border-radius:5px;font:11px var(--font-mono)}.v4-arrow{font:20px var(--font-display);padding-bottom:7px}.v4-go{margin-top:12px;width:100%;padding:10px;background:var(--gold);color:var(--card);border:0;border-radius:5px;font:11px var(--font-mono);cursor:pointer}.v4-empty{padding:14px;background:var(--bg);border-radius:6px;font:12px/1.5 var(--font-display);color:var(--text-sec);margin-top:12px}
 @media(max-width:620px){.v4-grid,.v4-cols{grid-template-columns:1fr}.v4-form{grid-template-columns:1fr}.v4-arrow{display:none}}
 `;document.head.appendChild(css);
 const wait=()=>new Promise(ok=>{let f=()=>document.querySelector('.node[data-eser]')&&document.getElementById('navBody')?ok():requestAnimationFrame(f);f()});await wait();
 const nodes=()=>[...document.querySelectorAll('.node[data-eser]')],esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let activeList=[];
 function clearLines(){document.querySelector('.v4-svg')?.remove()}
 function reset(){nodes().forEach(n=>n.classList.remove('v4-dim','v4-hit'));document.querySelector('.v4-path')?.remove();clearLines();activeList=[]}
 function available(list){return list.filter(x=>document.querySelector('.node[data-eser="'+CSS.escape(x)+'"]'))}
 function edgeLabel(a,b){let e=graph.edges.find(x=>(x[0]===a&&x[1]===b)||(x[0]===b&&x[1]===a));return e?e[2]:''}
 function drawLines(list){clearLines();let valid=available(list);if(valid.length<2)return;let svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','v4-svg');document.body.appendChild(svg);for(let i=0;i<valid.length-1;i++){let a=document.querySelector('.node[data-eser="'+CSS.escape(valid[i])+'"]'),b=document.querySelector('.node[data-eser="'+CSS.escape(valid[i+1])+'"]');if(!a||!b)continue;let ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),x1=ar.left+ar.width/2,y1=ar.top+ar.height/2,x2=br.left+br.width/2,y2=br.top+br.height/2,mx=(x1+x2)/2;let p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d','M '+x1+' '+y1+' C '+mx+' '+y1+', '+mx+' '+y2+', '+x2+' '+y2);svg.appendChild(p);[ [x1,y1],[x2,y2] ].forEach(([x,y])=>{let c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r','3');svg.appendChild(c)})}}
 function route(title,list,relations){reset();let valid=available(list),set=new Set(valid),first;nodes().forEach(n=>{let h=set.has(n.dataset.eser);n.classList.add(h?'v4-hit':'v4-dim');if(h&&!first)first=n});activeList=valid;let b=document.createElement('div');b.className='v4-path';let steps='';valid.forEach((x,i)=>{steps+='<span class="v4-step">'+(i+1)+'. '+esc(x)+'</span>';if(i<valid.length-1){let rel=relations?.[i]||edgeLabel(valid[i],valid[i+1]);steps+='<span class="v4-rel">→ '+esc(rel||'etki')+' →</span>'}});b.innerHTML='<div class="v4-path-title">'+esc(title)+'</div><div class="v4-steps">'+steps+' <button class="nav-btn" id="v4reset">Kapat</button></div>';document.body.appendChild(b);b.querySelector('#v4reset').onclick=reset;first?.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});setTimeout(()=>drawLines(valid),420)}
 window.addEventListener('resize',()=>activeList.length&&drawLines(activeList));window.addEventListener('scroll',()=>activeList.length&&drawLines(activeList),{passive:true});document.querySelector('.map-scroll')?.addEventListener('scroll',()=>activeList.length&&drawLines(activeList),{passive:true});
 function modal(k,t,l,body){document.querySelector('.v4-overlay')?.remove();let o=document.createElement('div');o.className='v4-overlay';o.innerHTML='<div class="v4-modal"><button class="v4-close">×</button><div class="v4-k">'+esc(k)+'</div><h2>'+esc(t)+'</h2><div class="v4-lead">'+esc(l)+'</div>'+body+'</div>';document.body.appendChild(o);o.querySelector('.v4-close').onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()};return o}
 const nav=document.getElementById('navBody'),sync=[...nav.querySelectorAll('.nav-row-label')].find(x=>x.textContent.trim()==='Senkron kodu');
 function section(title,buttons){let l=document.createElement('div');l.className='nav-row-label';l.textContent=title;let r=document.createElement('div');r.className='nav-row';buttons.forEach(([txt,fn])=>{let b=document.createElement('button');b.className='nav-btn nav-btn-wide';b.textContent=txt;b.onclick=fn;r.appendChild(b)});if(sync){nav.insertBefore(l,sync);nav.insertBefore(r,sync)}else nav.append(l,r)}
 // Eski V3 keşif ve fikir bölümlerini temizle; V4 tek kaynak olsun.
 [...nav.querySelectorAll('.nav-row-label')].forEach(l=>{if(['Fikirler','Keşif'].includes(l.textContent.trim())){let n=l.nextElementSibling;l.remove();if(n?.classList.contains('nav-row'))n.remove()}});
 section('Fikirler',ideas.map(i=>[i.label,()=>route('Fikir yolculuğu · '+i.label,i.eserler)]));
 function ask(){let o=modal('Soruyla keşfet','Büyük bir soruyla başla','Bir filozof adı bilmek zorunda değilsin. Sorunu seç; Atlas sana düşünce tarihindeki kısa yolu göstersin.','<div class="v4-grid">'+questions.map((q,i)=>'<button class="v4-choice" data-q="'+i+'">'+esc(q.soru)+'</button>').join('')+'</div>');o.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{let q=questions[+b.dataset.q];o.remove();route(q.soru,q.eserler)})}
 function graphNodes(){let s=new Set();graph.edges.forEach(e=>{if(document.querySelector('.node[data-eser="'+CSS.escape(e[0])+'"]'))s.add(e[0]);if(document.querySelector('.node[data-eser="'+CSS.escape(e[1])+'"]'))s.add(e[1])});return [...s]}
 function bfs(start,end){let adj={};graph.edges.forEach(([a,b,rel])=>{(adj[a]??=[]).push([b,rel]);(adj[b]??=[]).push([a,rel])});let q=[[start,[],[]]],seen=new Set([start]);while(q.length){let [cur,path,rels]=q.shift(),np=[...path,cur];if(cur===end)return {path:np,rels};for(let [nx,rel] of (adj[cur]||[])){if(!seen.has(nx)){seen.add(nx);q.push([nx,np,[...rels,rel]])}}}return null}
 function pathfinder(){let opts=graphNodes().sort((a,b)=>a.localeCompare(b,'tr')).map(x=>'<option>'+esc(x)+'</option>').join('');let o=modal('Düşünce yolu','Bir eserden diğerine nasıl geldik?','İki eser seç. Atlas, küratörlü etki grafiği içinde aradaki en kısa düşünce yolunu bulsun.','<div class="v4-form"><div class="v4-field"><label>Başlangıç</label><select id="v4from">'+opts+'</select></div><div class="v4-arrow">→</div><div class="v4-field"><label>Hedef</label><select id="v4to">'+opts+'</select></div></div><button class="v4-go" id="v4go">Düşünce yolunu bul</button><div id="v4msg"></div>');let from=o.querySelector('#v4from'),to=o.querySelector('#v4to');if([...to.options].some(x=>x.value==='Böyle Buyurdu Zerdüşt'))to.value='Böyle Buyurdu Zerdüşt';o.querySelector('#v4go').onclick=()=>{if(from.value===to.value){o.querySelector('#v4msg').innerHTML='<div class="v4-empty">Başlangıç ve hedef farklı olmalı.</div>';return}let r=bfs(from.value,to.value);if(!r){o.querySelector('#v4msg').innerHTML='<div class="v4-empty">Bu iki eser arasında henüz küratörlü bir bağlantı yok.</div>';return}o.remove();route(from.value+' → '+to.value,r.path,r.rels)}}
 function personal(){let st={};try{st=JSON.parse(localStorage.getItem('okuma-durumu')||'{}')}catch(e){}let all=nodes(),read=all.filter(n=>st[n.dataset.eser]),pct=all.length?Math.round(read.length/all.length*100):0;let ts=ideas.map(i=>{let a=i.eserler.filter(x=>all.some(n=>n.dataset.eser===x)),d=a.filter(x=>st[x]);return{label:i.label,p:a.length?Math.round(d.length/a.length*100):0,d:d.length,n:a.length}}).sort((a,b)=>b.p-a.p),strong=ts[0],open=[...ts].sort((a,b)=>a.p-b.p)[0];let suggestion=open?ideas.find(i=>i.label===open.label)?.eserler.find(x=>!st[x]&&document.querySelector('.node[data-eser="'+CSS.escape(x)+'"]')):null;let body='<div class="v4-ring" style="--p:'+pct+'%"><b>'+pct+'%</b></div><div class="v4-lead">'+read.length+' / '+all.length+' eser tamamlandı.<br>En güçlü fikir hattın: <b>'+esc(strong?.label||'—')+'</b> · Keşfe en açık alanın: <b>'+esc(open?.label||'—')+'</b>'+(suggestion?'<br>Buradan devam etmek için doğal durak: <b>'+esc(suggestion)+'</b>':'')+'</div>'+ts.map(t=>'<div class="v4-bar"><div class="v4-barhead"><span>'+esc(t.label)+'</span><span>'+t.d+'/'+t.n+' · %'+t.p+'</span></div><div class="v4-track"><div class="v4-fill" style="width:'+t.p+'%"></div></div></div>').join('');modal('Kişisel Atlas','Düşünce haritan','İlerlemeni sayıdan çok yönelim olarak oku: hangi sorulara dönüyorsun, hangi alanlar hâlâ boş?',body)}
 function worlds(){modal('Paralel zaman','Aynı anda dünyada','Bir düşünceyi doğduğu çağdan koparmadan gör. Aynı zaman diliminde farklı merkezlerde neler yaşandığını karşılaştır.',world.map(w=>'<div class="v4-world"><h3>'+esc(w.label)+'</h3><div class="v4-cols"><div class="v4-col"><b>BATI</b>'+esc(w.bati)+'</div><div class="v4-col"><b>DOĞU VE DİĞER MERKEZLER</b>'+esc(w.dogu)+'</div></div><div class="v4-event">↳ '+esc(w.olay)+'</div></div>').join(''))}
 section('Keşif',[['✦ Soruyla keşfet',ask],['↝ X → Y düşünce yolu',pathfinder],['◎ Kişisel Atlas',personal],['◫ Aynı anda dünyada',worlds]]);
 const card=document.createElement('aside');card.className='v4-card';document.body.appendChild(card);function jumpButtons(arr){return !arr?.length?'—':arr.map(x=>'<button class="v4-jump" data-jump="'+esc(x)+'">'+esc(x)+'</button>').join(' ')}
 function openCard(eser){let c=companion[eser];if(!c)return;let core=(c.fikirler||[]).slice(0,3);let effect=graph.edges.filter(e=>e[0]===eser||e[1]===eser).slice(0,3).map(e=>e[0]===eser?e[1]:e[0]);card.innerHTML='<button class="v4-close">×</button><div class="v4-k">Companion V3</div><h2>'+esc(eser)+'</h2><div class="v4-block"><label>Bu kitap hangi soruyu soruyor?</label><div>'+esc(c.anaFikir)+'</div></div><div class="v4-block"><label>60 saniyede kitap</label><div>'+esc(c.nedenOnemli)+'</div></div><div class="v4-block"><label>3 temel fikir</label><div class="v4-tags">'+core.map(x=>'<span class="v4-tag">'+esc(x)+'</span>').join('')+'</div></div><div class="v4-block"><label>Önce oku</label><div class="v4-tags">'+jumpButtons(c.once)+'</div></div><div class="v4-block"><label>Sonra oku</label><div class="v4-tags">'+jumpButtons(c.sonra)+'</div></div><div class="v4-block"><label>Atlas’taki yakın etkiler</label><div class="v4-tags">'+jumpButtons(effect)+'</div></div>';card.classList.add('open');card.querySelector('.v4-close').onclick=()=>card.classList.remove('open');card.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{let n=document.querySelector('.node[data-eser="'+CSS.escape(b.dataset.jump)+'"]');if(n){card.classList.remove('open');n.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});setTimeout(()=>openCard(b.dataset.jump),350)}})}
 document.addEventListener('click',e=>{let t=e.target.closest('.node .t');if(t&&companion[t.closest('.node')?.dataset.eser]){e.preventDefault();e.stopImmediatePropagation();openCard(t.closest('.node').dataset.eser)}},true);document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.v4-overlay')?.remove();card.classList.remove('open');reset()}})
})();
