(async function(){
  if(!window.matchMedia('(max-width:700px)').matches) return;
  document.body.classList.add('m2-active');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const roman=['I','II','III','IV','V','VI','VII','VIII','IX','X'];
  let western=[];
  try{western=await fetch('./data/western.json').then(r=>r.json())}catch(e){console.error(e)}
  const app=document.createElement('div');app.id='m2App';document.body.prepend(app);
  const bottom=document.createElement('nav');bottom.className='m2-bottom';bottom.innerHTML='<button class="m2-nav active" data-tab="atlas"><i>⌂</i>Atlas</button><button class="m2-nav" data-tab="discover"><i>✦</i>Keşfet</button><button class="m2-nav" data-tab="routes"><i>↝</i>Rotalar</button><button class="m2-nav" data-tab="me"><i>◎</i>Benim Atlasım</button>';document.body.appendChild(bottom);
  const waitNodes=()=>new Promise(ok=>{let n=0,f=()=>{if(document.querySelector('.node[data-eser]')||n++>100)return ok();setTimeout(f,60)};f()});await waitNodes();
  const desktopNode=eser=>document.querySelector('.node[data-eser="'+CSS.escape(eser)+'"]');
  const isRead=eser=>desktopNode(eser)?.classList.contains('read');
  const total=western.reduce((a,p)=>a+p.eserler.length,0);
  function countRead(){return western.reduce((a,p)=>a+p.eserler.filter(x=>isRead(x.eser)).length,0)}
  function header(){return `<div class="m2-top"><div class="m2-brandrow"><div class="m2-brand">Düşünce Atlası</div><button class="m2-desktop" id="m2Desktop">Masaüstü harita ↗</button></div><div class="m2-sub">10 dönem · düşünce tarihini dikey bir okuma rotası olarak keşfet</div><input class="m2-search" id="m2Search" placeholder="Eser veya yazar ara…"><div class="m2-progress"><span>Batı düşüncesi</span><b id="m2Progress">${countRead()} / ${total} okundu</b></div></div>`}
  function bookCard(b){let dn=desktopNode(b.eser),why=dn?.querySelector('.why')?.textContent?.trim()||'',read=isRead(b.eser);return `<article class="m2-book ${read?'is-read':''}" data-eser="${esc(b.eser)}" data-search="${esc((b.eser+' '+b.yazar).toLocaleLowerCase('tr'))}"><div class="m2-book-head"><div><div class="m2-book-title">${esc(b.eser)}</div><div class="m2-author">${esc(b.yazar)}</div></div><span class="m2-tag">${esc((b.kategori||'Felsefe').slice(0,3).toUpperCase())}</span></div>${why?`<div class="m2-why">${esc(why)}</div>`:''}<div class="m2-actions"><button class="m2-check" data-read="${esc(b.eser)}">${read?'✓ Okundu':'○ Okudum'}</button><button class="m2-detail" data-detail="${esc(b.eser)}">Detay →</button></div></article>`}
  function render(filter=''){let q=filter.trim().toLocaleLowerCase('tr'),sections='';western.forEach((p,i)=>{let books=p.eserler.filter(b=>!q||(b.eser+' '+b.yazar).toLocaleLowerCase('tr').includes(q));if(!books.length)return;sections+=`<details class="m2-era" ${q?'open':''}><summary><span class="m2-num">${roman[i]}</span><span><span class="m2-era-title">${esc(p.donem.replace(/^[IVX]+\.\s*/,''))}</span><span class="m2-era-meta">${esc(p.altbaslik)} · ${books.length} eser</span></span><span class="m2-chevron">›</span></summary><div class="m2-books">${books.map(bookCard).join('')}</div></details>`});app.innerHTML=header()+`<main class="m2-content"><div class="m2-intro">Bir dönemi aç, eserleri sırayla incele. Okuma durumun masaüstü haritayla aynı tutulur.</div>${sections||'<div class="m2-empty">Bu aramayla eşleşen eser bulunamadı.</div>'}</main>`;bindApp()}
  function bindApp(){app.querySelector('#m2Search').oninput=e=>render(e.target.value);app.querySelector('#m2Desktop').onclick=()=>{document.body.classList.add('m2-desktop-mode');window.scrollTo(0,0)};app.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>{let eser=b.dataset.read,n=desktopNode(eser),chk=n?.querySelector('.chk');if(chk){chk.click();setTimeout(()=>render(app.querySelector('#m2Search')?.value||''),80)}});app.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{let n=desktopNode(b.dataset.detail),t=n?.querySelector('.t');if(t){t.click()}else{sheet('Eser detayı','Bu eser için genişletilmiş Companion henüz eklenmedi.',[])}})}
  function findNav(label){return [...document.querySelectorAll('#navBody button')].find(b=>b.textContent.trim().toLocaleLowerCase('tr').includes(label.toLocaleLowerCase('tr')))}
  function trigger(label){let b=findNav(label);document.querySelector('.m2-sheet-bg')?.remove();if(b){b.click();return true}return false}
  function sheet(title,desc,items){document.querySelector('.m2-sheet-bg')?.remove();let bg=document.createElement('div');bg.className='m2-sheet-bg';bg.innerHTML=`<div class="m2-sheet"><div class="m2-grab"></div><h2>${esc(title)}</h2><p>${esc(desc)}</p><div class="m2-sheet-grid">${items.map(x=>`<button class="m2-sheet-btn ${x.wide?'wide':''}" data-label="${esc(x.find)}">${esc(x.label)}</button>`).join('')}</div></div>`;document.body.appendChild(bg);bg.onclick=e=>{if(e.target===bg)bg.remove()};bg.querySelectorAll('[data-label]').forEach(b=>b.onclick=()=>trigger(b.dataset.label))}
  function setTab(tab){bottom.querySelectorAll('.m2-nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='atlas'){document.querySelector('.m2-sheet-bg')?.remove();document.body.classList.remove('m2-desktop-mode');return}if(tab==='discover')sheet('Keşfet','Atlası bir soru, karşılaştırma veya zaman bağlamıyla keşfet.',[{label:'✦ Soruyla keşfet',find:'Soruyla keşfet',wide:true},{label:'⇄ Doğu × Batı',find:'Doğu × Batı'},{label:'◫ Aynı anda dünyada',find:'Aynı anda dünyada'},{label:'↔ Bağlantı lejandı',find:'Bağlantı lejandı',wide:true}]);if(tab==='routes')sheet('Rotalar','Hazır rotalardan birini seç veya iki eser arasında düşünce yolu kur.',[{label:'Temel Rota',find:'Temel Rota'},{label:'Batı Düşüncesi',find:'Batı Düşüncesi'},{label:'Doğu Düşüncesi',find:'Doğu Düşüncesi'},{label:'İktidarın Tarihi',find:'İktidarın Tarihi'},{label:'İyi Yaşam Rotası',find:'İyi Yaşam Rotası'},{label:'Modern İnsan Rotası',find:'Modern İnsan Rotası'},{label:'↝ X → Y düşünce yolu',find:'X → Y düşünce yolu',wide:true}]);if(tab==='me'){if(!trigger('Kişisel Atlas'))sheet('Benim Atlasım','Kişisel Atlas yüklenemedi.',[])}}
  bottom.querySelectorAll('.m2-nav').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
  render();
})();