(function(){
const west=[
['İyi yaşam nedir?',['erdem','polis','yurttaş'], 'Sokrates → Platon → Aristoteles','Atina demokrasisinin krizi → Makedon hâkimiyeti → Roma','İnsanı ve iyi yaşamı tartışırken soru giderek “iyi toplum nasıl kurulur?” problemine dönüşür.'],
['Birlikte nasıl yaşarız?',['adalet','yurttaşlık','iktidar'],'Platon → Aristoteles → Cicero','Polis → Cumhuriyet → İmparatorluk','Siyasal düzen çözüldükçe otoritenin kaynağı devletin ötesinde, inanç ve Tanrı üzerinden yeniden düşünülür.'],
['Akıl ile vahiy nasıl yan yana gelir?',['inanç','akıl','kurtuluş'],'Augustinus → Aquinas → skolastik gelenek','Roma’nın çöküşü → Kilise → üniversiteler','Skolastik sentezin sınırları görünür oldukça insan, doğa ve bilgi yeniden merkeze gelir.'],
['İnsan yeniden merkeze gelirse ne değişir?',['hümanizm','perspektif','güç'],'Machiavelli → Erasmus → Montaigne','Floransa → matbaa → Reform','Birey ve dünyevi iktidar öne çıktıkça meşruiyet artık gelenekten değil, sözleşmeden türetilmeye başlanır.'],
['Egemenlik kime aittir?',['hak','özgürlük','sözleşme'],'Hobbes → Locke → Rousseau','İç savaşlar → devrimler → anayasal düzen','Bireysel haklar siyasal düzenin temeli olur; sonraki soru bu özgür bireyin ekonomik dünyada nasıl yaşayacağıdır.'],
['Üretim insanı nasıl dönüştürür?',['emek','sınıf','piyasa'],'Smith → Marx → Tocqueville','Sanayi devrimi → kentleşme → sınıf çatışması','İlerleme fikri güçlenirken modern yaşamın yabancılaşma ve eşitsizlik üreten tarafları görünür olur.'],
['Akla olan güven kırılırsa ne kalır?',['nihilizm','bilinçdışı','yabancılaşma'],'Nietzsche → Freud → Weber','Metropol → kitle toplumu → I. Dünya Savaşı','İnsan artık tam rasyonel görülmez; savaş bu krizi varoluş ve özgürlük problemine dönüştürür.'],
['Yıkımdan sonra anlamı kim kurar?',['özgürlük','sorumluluk','anlam'],'Sartre → Camus → Arendt','Dünya savaşları → totalitarizm → soğuk savaş','Büyük anlatılar zayıfladıkça karar verme, belirsizlik ve davranışın gerçek mekanizmaları öne çıkar.'],
['Gerçekten rasyonel miyiz?',['karar','olasılık','önyargı'],'Kahneman → Tversky → modern davranış bilimi','İstatistik → finans → bilişsel bilim','İnsanın kararları kadar, ne gördüğü ve nasıl yönlendirildiği de temel meseleye dönüşür.'],
['Ne görüyoruz; bize ne gösteriliyor?',['imge','bakış','temsil'],'Berger → Benjamin → çağdaş görsel kültür','Fotoğraf → reklam → ekran toplumu','Atlas burada bugüne ulaşır: düşünce artık yalnız metinlerde değil, görüntüler ve medya düzenlerinde de şekillenir.']
];
const east=[
['İyi insan ilişkiler içinde nasıl kurulur?',['erdem','ritüel','uyum'],'Konfüçyüs → Mengzi → Xunzi','Zhou düzeninin çözülmesi → Savaşan Devletler','Toplumsal düzenin kaynağı bireysel erdemde aranırken bazı gelenekler düzen yerine doğayla uyumu öne çıkarır.'],
['İnsan doğayla uyumu nasıl bulur?',['dao','doğa','eylemsizlik'],'Laozi → Zhuangzi → Liezi','Merkezi düzen arayışı → geri çekilme → doğallık','Dış düzen yerine içsel serbestlik ve benlik sorusu belirginleşir.'],
['Benlik nedir; ondan özgürleşmek mümkün mü?',['benlik','acı','kurtuluş'],'Upanişadlar → Buda → Nagarjuna','Ritüelden içsel pratiğe → manastır gelenekleri','Hakikat ve kurtuluş arayışı sonraki yüzyıllarda akıl, vahiy ve sistematik bilgiyle yeniden birleşir.'],
['Bilgi gelenekler arasında nasıl taşınır?',['akıl','vahiy','hikmet'],'Kindi → Farabi → İbn Sina → İbn Rüşd','Bağdat tercüme hareketi → medreseler → Endülüs','Felsefi sentez kadar hakikatin deneyimlenmesi de önem kazanır; içsel yol güçlenir.'],
['Hakikate giden yol dışarıda mı içeride mi?',['tasavvuf','aşk','tecrübe'],'Gazali → Rumi → İbn Arabi','Kurumsal bilgi → mistik tecrübe → tarikatlar','İçsel tecrübe toplumsal düzen ve siyasal ahlak sorusuyla yeniden buluşur.'],
['Bilgi, iktidar ve gündelik hayat nasıl birleşir?',['şehir','ahlak','devlet'],'Nizamülmülk → İbn Haldun → Kınalızade','İmparatorluklar → şehir ağları → bürokrasi','Geleneksel düzen dışarıdan gelen teknoloji ve güç dengeleriyle karşılaşınca modernleşme sorunu doğar.'],
['Eski dünya yeni teknolojiyle nasıl karşılaşır?',['reform','teknoloji','kurum'],'Kâtip Çelebi → reformcular → modernleşmeciler','Matbaa → telgraf → demiryolu','Modernleşme artık teknik değil kimliksel bir soruya dönüşür: modern olmak ne demektir?'],
['Modern olmak Batılılaşmak mıdır?',['kimlik','eğitim','ulus'],'Tagore → İkbal → reformist düşünce','Sömürgecilik → üniversiteler → ulus-devletler','Bağımsızlık sonrası temel problem kendi sesini başkasının kategorilerinden geri almaktır.'],
['Kendini başkasının bakışından nasıl geri alırsın?',['sömürgecilik','temsil','adalet'],'Said → Sen → postkolonyal düşünce','Bağımsızlıklar → sınırlar → küreselleşme','Tek merkezli dünya tasavvuru çözülür; düşünce çok merkezli küresel ağlara taşınır.'],
['Tek merkezli dünya sona erdiğinde ne olur?',['ağ','göç','çoğulluk'],'Çağdaş Asya düşüncesi → küresel etik → çok merkezlilik','Mega kentler → dijital ağlar → göç','Atlas burada açık uçlu kalır: Doğu ve Batı artık ayrı kutuplar değil, sürekli etkileşen düşünce merkezleridir.']
];
function layer(){return document.getElementById('eastBtn')?.classList.contains('active')?'dogu':'western'}
function closeAll(){document.querySelectorAll('.period-inline').forEach(x=>x.remove());document.querySelectorAll('.period').forEach(x=>x.classList.remove('inline-open'));document.querySelectorAll('.period-inline-trigger').forEach(b=>b.textContent='30 saniyede anla ↓')}
function open(card,i){const d=(layer()==='dogu'?east:west)[i];if(!d)return;const existing=card.querySelector('.period-inline');if(existing){closeAll();return}closeAll();card.classList.add('inline-open');const trigger=card.querySelector('.period-inline-trigger');if(trigger)trigger.textContent='Kapat ↑';const box=document.createElement('div');box.className='period-inline';box.innerHTML='<div class="period-inline-grid"><div><div class="period-inline-k">TEMEL SORU</div><p class="period-inline-q">'+d[0]+'</p><div class="period-inline-tags">'+d[1].map(x=>'<span>'+x+'</span>').join('')+'</div></div><div><div class="period-inline-k">DÜŞÜNCE HATTI</div><div class="period-inline-flow">'+d[2].replaceAll('→','<b>→</b>')+'</div><div class="period-inline-k" style="margin-top:14px">TARİHSEL KIRILMA</div><div class="period-inline-flow">'+d[3].replaceAll('→','<b>→</b>')+'</div></div><div class="period-inline-next"><strong>Sonraki döneme bıraktığı problem:</strong> '+d[4]+'</div></div>';card.appendChild(box)}
function bind(){const periods=document.getElementById('periods');if(!periods)return false;[...periods.querySelectorAll('.period')].forEach((card,i)=>{if(card.querySelector('.period-inline-trigger'))return;const b=document.createElement('button');b.type='button';b.className='period-inline-trigger';b.textContent='30 saniyede anla ↓';b.onclick=e=>{e.stopPropagation();open(card,i)};card.appendChild(b)});return true}
let n=0;(function wait(){if(!bind()&&n++<120)setTimeout(wait,50)})();const p=document.getElementById('periods');if(p)new MutationObserver(()=>setTimeout(bind,0)).observe(p,{childList:true});document.getElementById('westBtn')?.addEventListener('click',()=>setTimeout(()=>{closeAll();bind()},30));document.getElementById('eastBtn')?.addEventListener('click',()=>setTimeout(()=>{closeAll();bind()},30));
})();
