(function(){
 const west=[['İnsan merkeze gelir','İyi yaşam ve erdem ilk büyük soru olur.'],['Siyaset doğar','Adalet, yurttaşlık ve devlet sistematik biçimde tartışılır.'],['İnanç düzen kurar','Antik akıl, vahiy ve teolojiyle yeniden yorumlanır.'],['İnsan geri döner','Rönesans bireyi, gücü ve dünyayı yeniden merkeze taşır.'],['Egemenlik halka iner','Haklar ve toplum sözleşmesi modern siyasetin dilini kurar.'],['Piyasa dünyayı değiştirir','Sanayi, sınıf ve kapitalizm yeni toplumsal sorular üretir.'],['Kesinlik kırılır','Nietzsche ve Freud modern insanın kendine güvenini sarsar.'],['Anlam yeniden aranır','Savaşlar sonrası özgürlük, sorumluluk ve varoluş öne çıkar.'],['Rasyonel insan çözülür','Davranış, risk ve karar verme yeni mercek olur.'],['Bakışın kendisi sorgulanır','Sanat, medya ve görme biçimleri düşüncenin konusu olur.']];
 const east=[['Erdem ilişkide kurulur','İyi insan, aile ve toplum içindeki ilişkileriyle düşünülür.'],['Yol doğaya döner','Uyum, sadelik ve müdahalesizlik güçlü bir alternatif sunar.'],['Benlik sorgulanır','Hint ve Budist gelenekler benlik, acı ve kurtuluşu merkeze alır.'],['Akıl ile vahiy buluşur','Bağdat ve çevresinde felsefe, bilim ve inanç büyük bir senteze girer.'],['İç dünya derinleşir','Tasavvuf bilgi sorununu deneyim ve dönüşüm üzerinden yeniden kurar.'],['Düzen yeniden düşünülür','Devlet, toplum ve tarih kendi dinamikleriyle açıklanmaya başlanır.'],['Gelenek moderniteyle karşılaşır','Matbaa, reform ve yeni kurumlar eski dengeleri değiştirir.'],['Modern Doğu konuşur','İkbal ve Tagore gibi isimler modernliği içeriden yeniden yorumlar.'],['Sömürge bakışı sorgulanır','Kimlik, temsil ve iktidar küresel tartışmanın merkezine gelir.'],['Merkezler çoğalır','Doğu artık tek bir karşı kutup değil, küresel düşüncenin çoklu merkezlerinden biridir.']];
 const compare=[
  ['Sokrates × Konfüçyüs','İyi insan nasıl yaşamalı?','Sorgulama ve erdem','Ritüel ve ilişkiler'],
  ['Stoacılık × Taoizm','Kontrol edemediğimiz dünyayla nasıl yaşarız?','İçsel hâkimiyet','Akışla uyum'],
  ['Augustinus × İbn Sina','Akıl ile inanç nasıl buluşur?','İçe dönüş ve vahiy','Felsefe ve vahiy'],
  ['Montaigne × Zen','Benlik ne kadar sabittir?','Kendini gözlemlemek','Benlik fikrini çözmek'],
  ['Mill × Tagore','Özgürlük tek biçimli midir?','Bireysel özgürlük','Kültürel çoğulluk'],
  ['Berger × Said','Bakış tarafsız olabilir mi?','Görme rejimleri','Temsil ve iktidar']
 ];
 function mode(){if(document.getElementById('compareBtn')?.classList.contains('active')||new URLSearchParams(location.search).get('katman')==='karsilastir')return'compare';return document.getElementById('eastBtn')?.classList.contains('active')?'east':'west'}
 function render(){const periods=document.getElementById('periods');if(!periods)return;document.querySelector('.story2500')?.remove();const m=mode(),s=document.createElement('section');s.className='story2500'+(m==='compare'?' story2500-compare':'');if(m==='compare'){
   s.innerHTML='<div class="story2500-head"><div><div class="story2500-k">Doğu × Batı · 6 karşılaşma</div><h2>Bir bakışta paralel sorular</h2></div><div class="story2500-copy">Aynı çağlarda benzer insanlık sorularının iki düşünce geleneğinde nasıl farklı cevaplara dönüştüğünü yan yana oku.</div></div><div class="story2500-track">'+compare.map((x,i)=>'<article class="story2500-step compare-story-step"><div class="story2500-num">'+String(i+1).padStart(2,'0')+'</div><h3>'+x[0]+'</h3><p class="compare-question">'+x[1]+'</p><div class="compare-mini"><span><b>BATI</b>'+x[2]+'</span><i>×</i><span><b>DOĞU</b>'+x[3]+'</span></div></article>').join('')+'</div>';
  }else{const data=m==='east'?east:west;s.innerHTML='<div class="story2500-head"><div><div class="story2500-k">2.500 yıl · 10 kırılma</div><h2>Bir bakışta düşüncenin dönüşümü</h2></div><div class="story2500-copy">Dönemleri ayrı kutular olarak değil, birbirini doğuran on büyük kırılma olarak oku. Her adım bir öncekinin bıraktığı probleme yeni bir cevap verir.</div></div><div class="story2500-track">'+data.map((x,i)=>'<article class="story2500-step"><div class="story2500-num">'+String(i+1).padStart(2,'0')+'</div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></article>').join('')+'</div>'}
  periods.parentNode.insertBefore(s,periods);s.querySelectorAll('.story2500-step').forEach((el,i)=>el.onclick=()=>periods.children[i]?.scrollIntoView({behavior:'smooth',block:'center'}))}
 let timer;const obs=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(render,60)});function init(){if(!document.getElementById('periods'))return requestAnimationFrame(init);render();obs.observe(document.getElementById('periods'),{childList:true});document.getElementById('westBtn')?.addEventListener('click',()=>setTimeout(render,140));document.getElementById('eastBtn')?.addEventListener('click',()=>setTimeout(render,140));document.addEventListener('click',e=>{if(e.target.closest('#compareBtn'))setTimeout(render,80)},true)}init();
})();