(async function(){
  const [graph,periods]=await Promise.all([
    fetch('./data/dusunceGrafi.json').then(r=>r.json()),
    fetch('./data/donemBaglam.json').then(r=>r.json())
  ]);
  const typeLabels={dogrudan_etki:'Doğrudan etki',elestiri_cevap:'Eleştiri / cevap',gelenek_devami:'Gelenek devamı',kavramsal_gecis:'Kavramsal geçiş',karsilastirma:'Karşılaştırma'};
  const typeHelp={dogrudan_etki:'Belgelenebilir düşünsel etki veya yakın entelektüel miras.',elestiri_cevap:'Önceki görüşe açık eleştiri, düzeltme veya cevap.',gelenek_devami:'Aynı düşünce geleneğinin belirgin biçimde geliştirilmesi.',kavramsal_gecis:'Doğrudan tarihsel etki iddiası olmadan anlamlı kavramsal köprü.',karsilastirma:'Benzer probleme farklı yaklaşım; etki iddiası içermez.'};
  const periodTitles=['I. İnsanı Anlamak','II. Devlet ve Toplum','III. İnanç ve Orta Çağ','IV. Rönesans ve Güç','V. Toplum Sözleşmesi','VI. Kapitalizm ve Sanayi','VII. Modernitenin Krizi','VIII. Savaş, Anlam ve Özgürlük','IX. Akıl, Risk ve Davranış','X. Sanat ve Görme Biçimleri'];
  const periodQuestions=['İyi insan nasıl yaşamalı?','Adil bir toplum nasıl kurulmalı?','İnanç ile akıl nasıl uzlaştırılmalı?','İktidar gerçekte nasıl işler?','Meşru siyasal düzen nereden doğar?','Piyasa, sınıf ve özgürlük nasıl ilişkilidir?','Modern insan neden kendine yabancılaşır?','Kriz ve anlamsızlık karşısında nasıl yaşanır?','İnsan gerçekten ne kadar rasyoneldir?','Görme ve temsil dünyayı nasıl kurar?'];
  const recommended=[["Sokrates'in Savunması",'Devlet',"Nikomakhos'a Etik"],['Devlet','Politika','Devlet Üzerine'],['İtiraflar','Felsefenin Tesellisi','Summa Theologica'],['Deliliğe Övgü','Prens','Ütopya'],['Leviathan','Yönetim Üzerine İki İnceleme','Toplum Sözleşmesi'],['Ulusların Zenginliği',"Amerika'da Demokrasi",'Özgürlük Üzerine'],['Böyle Buyurdu Zerdüşt','Ahlakın Soykütüğü','Düşlerin Yorumu'],['Sisifos Söyleni','İnsanın Anlam Arayışı','Özgürlükten Kaçış'],['Hızlı ve Yavaş Düşünme','Dürtme','Siyah Kuğu'],['Görme Biçimleri','Fotoğraf Üzerine','Simülakrlar ve Simülasyon']];
  const css=document.createElement('style');css.textContent=`.v7-badge{display:inline-flex;align-items:center;gap:5px;margin-top:7px;padding:4px 7px;border:1px solid var(--border);border-radius:10px;font:600 8.5px/1 var(--font-mono);color:var(--text-sec);white-space:nowrap}.v7-badge strong{color:var(--gold);font-weight:600}.route-readable .route-link{position:relative;cursor:help}.v7-tip{display:none;position:absolute;bottom:calc(100% + 8px);left:50%;transform:translateX(-50%);width:245px;padding:10px 11px;background:var(--card);border:1px solid var(--gold);border-radius:7px;box-shadow:0 10px 30px #0008;z-index:4;text-align:left;font:10px/1.45 var(--font-mono);color:var(--text)}.route-readable .route-link:hover .v7-tip{display:block}.v7-tip b{color:var(--gold);display:block;margin-bottom:4px}.v7-share{border:1px solid var(--border);background:transparent;color:var(--text);border-radius:7px;padding:8px 11px;font:600 10px var(--font-mono);cursor:pointer;margin-right:6px}.v7-share:hover{border-color:var(--gold);color:var(--gold)}.v7-legend{display:grid;gap:7px}.v7-legend-row{display:grid;grid-template-columns:105px 1fr auto;gap:10px;align-items:center;padding:9px;border-bottom:.5px solid var(--border);font:10px/1.4 var(--font-mono)}.v7-line{height:2px;background:var(--gold)}.v7-line.kavramsal_gecis{background:repeating-linear-gradient(90deg,var(--gold) 0 6px,transparent 6px 11px)}.v7-line.karsilastirma{background:repeating-linear-gradient(90deg,var(--text-sec) 0 3px,transparent 3px 7px)}.v7-confidence{color:var(--text-sec);white-space:nowrap}.col-title.v7-period{cursor:pointer;text-decoration-thickness:1px;text-underline-offset:3px}.col-title.v7-period:hover{color:var(--gold);text-decoration:underline}.v7-period-body{font:16px/1.7 var(--font-display);color:var(--text);max-width:760px}.v7-question{margin:17px 0;padding:13px 15px;border-left:2px solid var(--gold);background:var(--bg);font:italic 18px/1.45 var(--font-display)}.v7-recs{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:15px}.v7-rec{padding:11px;background:var(--bg);border:1px solid var(--border);border-radius:6px;font:12px/1.35 var(--font-display)}.v7-rec span{display:block;font:8px var(--font-mono);color:var(--gold);margin-bottom:5px;text-transform:uppercase}@media(max-width:650px){.v7-recs{grid-template-columns:1fr}.v7-tip{display:none!important}}`;document.head.appendChild(css);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const slug=s=>String(s).toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const edge=(a,b)=>graph.edges.find(e=>(e[0]===a&&e[1]===b)||(e[0]===b&&e[1]===a));
  function modal(k,t,l,body){document.querySelector('.v7-overlay')?.remove();let o=document.createElement('div');o.className='v5-overlay v7-overlay';o.innerHTML='<div class="v5-modal"><button class="v5-close">×</button><div class="v5-k">'+esc(k)+'</div><h2>'+esc(t)+'</h2><div class="v5-lead">'+esc(l)+'</div>'+body+'</div>';document.body.appendChild(o);o.querySelector('.v5-close').onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()};return o}
  function enhanceRoute(path){if(!path?.classList.contains('route-readable')||path.dataset.v7==='1')return;path.dataset.v7='1';const cards=[...path.querySelectorAll('.route-card')],links=[...path.querySelectorAll('.route-link')];links.forEach((l,i)=>{const a=cards[i]?.querySelector('.route-title')?.textContent.trim(),b=cards[i+1]?.querySelector('.route-title')?.textContent.trim(),e=edge(a,b);if(!e)return;const type=e[3],conf=e[4],label=typeLabels[type]||type;l.insertAdjacentHTML('beforeend','<div class="v7-badge"><strong>'+esc(label)+'</strong> · '+esc(conf)+' güven</div><div class="v7-tip"><b>'+esc(label)+' · '+esc(conf)+' güven</b>'+esc(typeHelp[type]||'')+'<br><br>'+esc(e[2])+'</div>')});const head=path.querySelector('.route-head');if(head&&!head.querySelector('.v7-share')){const close=head.querySelector('.route-close'),share=document.createElement('button');share.className='v7-share';share.textContent='Bağlantıyı kopyala';share.onclick=async()=>{const title=path.querySelector('h3')?.textContent||'',steps=cards.map(c=>c.querySelector('.route-title')?.textContent.trim()).filter(Boolean),u=new URL(location.href);u.search='';if(title.startsWith('Fikir yolculuğu · '))u.searchParams.set('fikir',slug(title.split('·').slice(1).join('·').trim()));else if(steps.length>=2)u.searchParams.set('yol',steps[0]+'~'+steps[steps.length-1]);try{await navigator.clipboard.writeText(u.toString());share.textContent='Kopyalandı ✓';setTimeout(()=>share.textContent='Bağlantıyı kopyala',1400)}catch(e){location.href=u.toString()}};close?.before(share)}}
  const obs=new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType!==1)return;if(n.matches?.('.v5-path'))setTimeout(()=>enhanceRoute(n),0);n.querySelectorAll?.('.v5-path').forEach(x=>setTimeout(()=>enhanceRoute(x),0))})));obs.observe(document.body,{childList:true,subtree:true});document.querySelectorAll('.v5-path').forEach(enhanceRoute);
  function showLegend(){modal('Bağlantı lejandı','Çizgiler ne anlama geliyor?','Her bağlantı aynı güçte bir tarihsel etki iddiası taşımaz. Tür ve güven seviyesi bunu açıkça gösterir.','<div class="v7-legend">'+Object.keys(typeLabels).map(k=>'<div class="v7-legend-row"><div class="v7-line '+k+'"></div><div><b>'+esc(typeLabels[k])+'</b><br>'+esc(typeHelp[k])+'</div><div class="v7-confidence">edge bazlı güven</div></div>').join('')+'</div>')}
  function installLegend(){const nav=document.getElementById('navBody');if(!nav||document.getElementById('v7LegendBtn'))return;const sync=[...nav.querySelectorAll('.nav-row-label')].find(x=>x.textContent.trim()==='Senkron kodu');const l=document.createElement('div');l.className='nav-row-label';l.textContent='Bağlantılar';const r=document.createElement('div');r.className='nav-row';const b=document.createElement('button');b.id='v7LegendBtn';b.className='nav-btn nav-btn-wide';b.textContent='↔ Bağlantı lejandı';b.onclick=showLegend;r.appendChild(b);nav.insertBefore(l,sync);nav.insertBefore(r,sync)}
  function installPeriods(){[...document.querySelectorAll('.col-title')].slice(0,10).forEach((el,i)=>{el.classList.add('v7-period');el.title='Dönem hikâyesini aç';el.onclick=()=>{const recs=(recommended[i]||[]).map((x,j)=>'<div class="v7-rec"><span>'+(j+1)+'. başlangıç eseri</span>'+esc(x)+'</div>').join('');modal('Dönem '+(i+1),periodTitles[i],periodQuestions[i],'<div class="v7-period-body">'+esc(periods[i]||'')+'</div><div class="v7-question">'+esc(periodQuestions[i])+'</div><div class="v5-k">Bu döneme nereden girilir?</div><div class="v7-recs">'+recs+'</div>')}})}
  async function waitUI(){for(let i=0;i<120;i++){if(document.getElementById('navBody')&&document.querySelectorAll('.col-title').length>=10)return;await new Promise(r=>setTimeout(r,50))}}await waitUI();installLegend();installPeriods();
  async function restoreFromUrl(){const p=new URLSearchParams(location.search);if(p.has('fikir')){const target=p.get('fikir'),btn=[...document.querySelectorAll('#navBody .nav-btn')].find(b=>slug(b.textContent)===target);btn?.click();return}if(p.has('yol')){const [a,z]=p.get('yol').split('~'),btn=[...document.querySelectorAll('#navBody .nav-btn')].find(b=>b.textContent.includes('X → Y'));if(!btn||!a||!z)return;btn.click();await new Promise(r=>setTimeout(r,80));const from=document.querySelector('.v5-overlay #from'),to=document.querySelector('.v5-overlay #to');if(from&&to){from.value=a;to.value=z;document.querySelector('.v5-overlay #go')?.click()}}}setTimeout(restoreFromUrl,180);
})();
